version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: scena
      POSTGRES_USER: scena
      POSTGRES_PASSWORD: gKJFjuh4ARNyP9zrk6ZVX*8mdNByU7Hi
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure

  kratos-migrate:
    image: oryd/kratos:v0.10.1
    container_name: kratos-migrate
    environment:
      - DSN=postgres://kratos:password@kratos-db:5432/kratos?sslmode=disable
    volumes:
      - ./kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    image: oryd/kratos:v0.10.1
    container_name: kratos
    depends_on:
      - kratos-migrate
    ports:
      - 4433:4433
      - 4434:4434
    environment:
      - DSN=postgres://kratos:password@kratos-db:5432/kratos?sslmode=disable
      - LOG_LEVEL=trace
    volumes:
      - ./kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: on-failure

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.10.1
    container_name: kratos-sefservice-ui-node
    ports:
      - 4455:4455
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost:4433/
    restart: on-failure

  kratos-db:
    image: postgres:latest
    container_name: kratos-db
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kratos
    volumes:
      - kratos_db_data:/var/lib/postgresql/data
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    restart: on-failure

volumes:
  db_data:
  kratos_db_data:
